<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="1" time="0.117" timestamp="2021-04-19T16:50:52.971224" hostname="dlg-air"><testcase classname="tests.test_lfu" name="test_lfu_maxsize_violation_regression" time="0.001"><failure message="assert [1, 2, 3, 4, 5, 6] == [1, 2, 4, 6]">def test_lfu_maxsize_violation_regression():
        """Test that LFUCache doesn't allow maxsize violation."""
        cache = LFUCache(maxsize=4)
    
        for _ in range(4):
            cache.add(1, 1)
            cache.add(2, 1)
    
        for _ in range(3):
            cache.add(3, 1)
            cache.add(4, 1)
    
        cache.add(5, 1)
        cache.add(6, 1)
    
&gt;       assert list(cache.keys()) == [1, 2, 4, 6]
E       assert [1, 2, 3, 4, 5, 6] == [1, 2, 4, 6]

test_lfu.py:88: AssertionError</failure></testcase></testsuite></testsuites>